{
 "title": "Sus Connect - Network Service Dashboard",
 "tags": [
  "sus-connect",
  "spring-boot"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sus Connect - Governança da Rede",
   "type": "row",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(system_cpu_usage) * 100" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count)"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds_max) * 1000"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Métricas Operacionais (Escalabilidade e Tráfego)",
   "type": "row",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Throughput por Endpoint (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{uri}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Latência P95 (Tempo de Resposta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95 Latency"
    }
   ]
  }
 ]
}